from enum import Enum


class SourceLangs(str, Enum):
    """Source language options for DeepL translation"""
    any = "Any"
    arabic = "AR"
    bulgarian = "BG"
    czech = "CS"
    danish = "DA"
    german = "DE"
    greek = "EL"
    english = "EN"
    spanish = "ES"
    estonian = "ET"
    finnish = "FI"
    french = "FR"
    hungarian = "HU"
    indonesian = "ID"
    italian = "IT"
    japanese = "JA"
    korean = "KO"
    lithuanian = "LT"
    latvian = "LV"
    norwegian_bokmal = "NB"
    dutch = "NL"
    polish = "PL"
    portuguese = "PT"
    romanian = "RO"
    russian = "RU"
    slovak = "SK"
    slovenian = "SL"
    swedish = "SV"
    turkish = "TR"
    ukrainian = "UK"
    chinese = "ZH"