from enum import Enum


class TargetLangs(str, Enum):
    """Target language options for DeepL translation"""
    arabic = "AR"
    bulgarian = "BG"
    czech = "CS"
    danish = "DA"
    german = "DE"
    greek = "EL"
    english_gb = "EN-GB"
    english_us = "EN-US"
    spanish = "ES"
    estonian = "ET"
    finnish = "FI"
    french = "FR"
    hungarian = "HU"
    indonesian = "ID"
    italian = "IT"
    japanese = "JA"
    korean = "KO"
    lithuanian = "LT"
    latvian = "LV"
    norwegian_bokmal = "NB"
    dutch = "NL"
    portuguese_br = "PT-BR"
    portuguese_pt = "PT-PT"
    romanian = "RO"
    russian = "RU"
    slovak = "SK"
    slovenian = "SL"
    swedish = "SV"
    turkish = "TR"
    ukrainian = "UK"
    chinese = "ZH-HANT"
    chinese_simplified = "ZH-HANS"